<a href="https://colab.research.google.com/github/Harish-aditya/100_numpy_exercises/blob/main/Numpy_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2], dtype = 'int16')
a

array([1, 2], dtype=int16)

In [3]:
a2 = np.array([[1,2],[3,4]],dtype = 'int32')
a2

array([[1, 2],
       [3, 4]], dtype=int32)

In [4]:
a3 = np.array([[[1,2],[3,4],[5,6]]],dtype = 'int64')
a3

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [5]:
# get dimension
print(a.ndim,a2.ndim,a3.ndim)

1 2 3


In [6]:
# get shape
print(a.shape,a2.shape,a3.shape)

(2,) (2, 2) (1, 3, 2)


In [7]:
# get dtype
print(a.dtype,a2.dtype,a3.dtype)

int16 int32 int64


In [8]:
# get itemsize
print(a.itemsize,a2.itemsize,a3.itemsize)

2 4 8


In [9]:
# get total size
print(a.size,a2.size,a3.size)

2 4 6


In [10]:
# get number of bytes (itemsize*size)
print(a.nbytes,a2.nbytes,a3.nbytes)

4 16 48


Acessing, changing specific rows, elements, columns. etc.,

In [11]:
b = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [12]:
# get a specific element [r,c]
b[1,5]

13

In [13]:
# get a specific row
b[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [14]:
# get a specific column
b[:,3]

array([ 4, 11])

In [15]:
#skipping index [start:end:step]
b[0,1:6:3]

array([2, 5])

In [16]:
#replacing a specific value
b[1,5] = 20
print(b)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [17]:
# replacing a group of values
b[0,4:6]=[1,2]
print(b)

[[ 1  2  3  4  1  2  7]
 [ 8  9 10 11 12 20 14]]


In [18]:
a3

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [19]:
# 3d array
a3.shape

(1, 3, 2)

In [20]:
# get specific element (work outside in)
a3[0,2,0]

5

Initialzing different types of array

In [21]:
# all zeros matrix
c = np.zeros(3)
c1 = np.zeros([2,2])
c2 = np.zeros([3,3,3])

In [22]:
print(c,c1,c2, sep = '\n')

[0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [23]:
# ones
d = np.ones(3)
d1 = np.ones([2,2])
d2 = np.ones([3,3,3])

In [24]:
print(d,d1,d2, sep = '\n')

[1. 1. 1.]
[[1. 1.]
 [1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [27]:
# full values
d3 = np.full((2,2),9,dtype="float32")
d3

array([[9., 9.],
       [9., 9.]], dtype=float32)

In [30]:
# any other full_like
d4 = np.full_like(b,4)
d4

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [38]:
# random decimal numbers
d5 = np.random.rand(10,10)
d5

array([[0.8998018 , 0.34615063, 0.92667243, 0.37384809, 0.11432602,
        0.64752828, 0.50619941, 0.65018868, 0.58540374, 0.05633983],
       [0.7450565 , 0.03518604, 0.9672945 , 0.63606112, 0.30159286,
        0.97695454, 0.53431805, 0.40584482, 0.91510425, 0.73880904],
       [0.17442972, 0.85729664, 0.5781111 , 0.219402  , 0.27573478,
        0.33131898, 0.64885378, 0.2893561 , 0.12162071, 0.56295659],
       [0.92917455, 0.85789223, 0.96374584, 0.52151808, 0.91301197,
        0.51791513, 0.57478443, 0.71112544, 0.66412583, 0.7758393 ],
       [0.24733401, 0.71630912, 0.40030108, 0.82165134, 0.50690612,
        0.52127337, 0.58212476, 0.11949994, 0.27450754, 0.88645794],
       [0.12091717, 0.03931791, 0.87148479, 0.90073276, 0.9821132 ,
        0.80528013, 0.2955074 , 0.65562294, 0.47405706, 0.29829795],
       [0.49363384, 0.9306858 , 0.53964999, 0.74962978, 0.22251518,
        0.57174675, 0.71206806, 0.88624505, 0.60549696, 0.74854749],
       [0.74886609, 0.4494633 , 0.9138376