<a href="https://colab.research.google.com/github/Harish-aditya/100_numpy_exercises/blob/main/Numpy_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### basics

In [1]:
import numpy as np

In [2]:
a = np.array([1,2], dtype = 'int16')
a

array([1, 2], dtype=int16)

In [3]:
a2 = np.array([[1,2],[3,4]],dtype = 'int32')
a2

array([[1, 2],
       [3, 4]], dtype=int32)

In [4]:
a3 = np.array([[[1,2],[3,4],[5,6]]],dtype = 'int64')
a3

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [5]:
# get dimension
print(a.ndim,a2.ndim,a3.ndim)

1 2 3


In [6]:
# get shape
print(a.shape,a2.shape,a3.shape)

(2,) (2, 2) (1, 3, 2)


In [7]:
# get dtype
print(a.dtype,a2.dtype,a3.dtype)

int16 int32 int64


In [8]:
# get itemsize
print(a.itemsize,a2.itemsize,a3.itemsize)

2 4 8


In [9]:
# get total size
print(a.size,a2.size,a3.size)

2 4 6


In [10]:
# get number of bytes (itemsize*size)
print(a.nbytes,a2.nbytes,a3.nbytes)

4 16 48


Acessing, changing specific rows, elements, columns. etc.,

In [11]:
b = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [12]:
# get a specific element [r,c]
b[1,5]

13

In [13]:
# get a specific row
b[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [14]:
# get a specific column
b[:,3]

array([ 4, 11])

In [15]:
#skipping index [start:end:step]
b[0,1:6:3]

array([2, 5])

In [16]:
#replacing a specific value
b[1,5] = 20
print(b)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [17]:
# replacing a group of values
b[0,4:6]=[1,2]
print(b)

[[ 1  2  3  4  1  2  7]
 [ 8  9 10 11 12 20 14]]


In [18]:
a3

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [19]:
# 3d array
a3.shape

(1, 3, 2)

In [20]:
# get specific element (work outside in)
a3[0,2,0]

5

Initialzing different types of array

In [21]:
# all zeros matrix
c = np.zeros(3)
c1 = np.zeros([2,2])
c2 = np.zeros([3,3,3])

In [22]:
print(c,c1,c2, sep = '\n')

[0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [23]:
# ones
d = np.ones(3)
d1 = np.ones([2,2])
d2 = np.ones([3,3,3])

In [24]:
print(d,d1,d2, sep = '\n')

[1. 1. 1.]
[[1. 1.]
 [1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [25]:
# full values
d3 = np.full((2,2),9,dtype="float32")
d3

array([[9., 9.],
       [9., 9.]], dtype=float32)

In [26]:
# any other full_like
d4 = np.full_like(b,4)
d4

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [27]:
# random decimal numbers
d5 = np.random.rand(10,10)
d5

array([[0.09086901, 0.24035986, 0.01664757, 0.31185805, 0.83962801,
        0.30100649, 0.99777737, 0.02209399, 0.03194573, 0.51109935],
       [0.95952898, 0.46237745, 0.23146901, 0.70612845, 0.06178554,
        0.76096617, 0.34507994, 0.46014182, 0.83857753, 0.70019621],
       [0.56148652, 0.88956811, 0.89451949, 0.83462347, 0.06232699,
        0.95449729, 0.6390497 , 0.95028563, 0.15375719, 0.32770413],
       [0.21856143, 0.59125971, 0.06365567, 0.71370776, 0.63583832,
        0.58679006, 0.11695668, 0.95308217, 0.85577842, 0.31486915],
       [0.99234042, 0.13704954, 0.66745927, 0.29401293, 0.88002729,
        0.44727384, 0.75500572, 0.91281537, 0.50441779, 0.06239059],
       [0.55694426, 0.48833107, 0.50486905, 0.14161918, 0.82577732,
        0.55591789, 0.15037489, 0.48827807, 0.91672156, 0.42107579],
       [0.03036729, 0.58518539, 0.3404697 , 0.3158562 , 0.31480567,
        0.79959563, 0.362591  , 0.33112702, 0.55813508, 0.41987696],
       [0.51881661, 0.91937183, 0.7694083

In [28]:
d6 = np.random.randint(10,100,size = (4,4))
d6

array([[85, 32, 90, 97],
       [98, 52, 38, 57],
       [19, 61, 20, 40],
       [22, 25, 34, 24]])

In [29]:
# to create a array with a predefined shape.
d7 = np.random.random_sample(a.shape)
d7

array([0.82275951, 0.28065348])

In [30]:
# to create an identity matrix
d8 = np.identity(3)
d8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
# to repeat an array multiple times.
arr = np.array([1,2,3])
r1 = np.repeat(arr,3,axis = 0)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [32]:

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [33]:
op = np.ones((5,5))
op

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
z[1,1]=9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [36]:
op[1:4,1:4]=z
op

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Be careful when copying arrays.


In [37]:
e = np.array([1,2,3])
f = e
print(f,e)
f[0] = 100


[1 2 3] [1 2 3]


In [38]:
f,e

(array([100,   2,   3]), array([100,   2,   3]))

In [39]:
e = np.array([1,2,3])
f = e.copy()
print(f,e)
f[0] = 100

[1 2 3] [1 2 3]


In [40]:
f,e

(array([100,   2,   3]), array([1, 2, 3]))

### mathematics

In [41]:
e1 = np.array([1,2,3,4])
e1

array([1, 2, 3, 4])

In [42]:
e1 += 3
e1

array([4, 5, 6, 7])

In [43]:
e1 - 2

array([2, 3, 4, 5])

In [44]:
e1 * 3

array([12, 15, 18, 21])

In [45]:
e1/3

array([1.33333333, 1.66666667, 2.        , 2.33333333])

In [46]:
e1 ** 2

array([16, 25, 36, 49])

In [47]:
# take the cos, sin of the array
e2 = np.cos(e1)
e2

array([-0.65364362,  0.28366219,  0.96017029,  0.75390225])

In [48]:
f1 = np.ones((2,3))
print(f1)

f2 = np.full((3,2),2)
print(f2)

f4 = np.matmul(f1,f2)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [49]:
# find the determinant
f3 = np.identity(3)
np.linalg.det(f3),np.linalg.det(f4)

(1.0, 0.0)

determinant,
trace,
single vector displacement,
eigenvalues,
matrixnorm,
inverse,

### statistics

In [50]:
g = np.array([[1,2,3],[2,3,4]])
np.min(g)

1

In [51]:
np.min(g,axis = 0)

array([1, 2, 3])

In [52]:
np.min(g,axis = 1)

array([1, 2])

In [53]:
np.max(g)

4

In [54]:
np.max(g,axis = 0)

array([2, 3, 4])

In [55]:
np.max(g,axis = 1)

array([3, 4])

In [56]:
np.mean(g,axis = 1)

array([2., 3.])

### Reorganizing arrays

In [57]:
bf = np.array([[1,2,3,4],[5,6,7,8]])
print(bf,bf.shape)

[[1 2 3 4]
 [5 6 7 8]] (2, 4)


In [58]:
af1 = bf.reshape((4,2))
af2 = bf.reshape((2,2,2))
print(af1,af2,sep = "\n")

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


vertically stacking vectors

In [59]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

horizontal stacking vectors

In [60]:
np.hstack([v1,v2,v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

### Miscellaneous

In [67]:
dd = np.genfromtxt('/content/testt.txt', delimiter = ',')

In [68]:
dd.astype('int32')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9,  0, 10,  1,  2,  3,  4,  5,  6,
        7,  8,  9,  0, 11], dtype=int32)