# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__,np.show_config)

1.21.6 <function show at 0x7f1c34d7c440>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
print(np.size(x),x.itemsize)

10 8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info('add')

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is creat

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
x1 = np.arange(10,49)
x1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
x1[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
x2 = np.arange(0,9)
x2.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
x3 = [1,2,0,0,4,0]
np.nonzero(x3)#returns a array of indices of non-zero elements.

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
i = np.eye(3,3,order = 'c')#returns a identity matrix
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
np.random.random([3,3,3])

array([[[0.06923301, 0.96617448, 0.40064813],
        [0.74966653, 0.44548346, 0.4033208 ],
        [0.6339939 , 0.12804635, 0.3298827 ]],

       [[0.39278063, 0.1867951 , 0.91467187],
        [0.69991268, 0.87873349, 0.43613911],
        [0.50490394, 0.21021839, 0.66129269]],

       [[0.07751607, 0.49430954, 0.83119837],
        [0.84131844, 0.54929759, 0.31986791],
        [0.2172553 , 0.4026211 , 0.31473479]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
x4 = np.random.random([10,10])
x4
print(x4,x4.min(),x4.max())

[[0.29856476 0.87363899 0.2909255  0.02653457 0.50173779 0.61317583
  0.33856945 0.22768049 0.26168921 0.59148073]
 [0.77384801 0.46998706 0.00365819 0.00598029 0.54745306 0.18825418
  0.29232085 0.1244892  0.31870066 0.25324301]
 [0.74289655 0.0300608  0.53196444 0.128683   0.75210265 0.57656625
  0.79662003 0.0533574  0.08039127 0.68356611]
 [0.02518937 0.00408745 0.64520959 0.12088849 0.5734801  0.46713621
  0.56024118 0.90228752 0.06939328 0.70219487]
 [0.37332323 0.15738982 0.53328543 0.23088218 0.84781434 0.29149585
  0.95378537 0.59016705 0.20282374 0.0372066 ]
 [0.99213154 0.29402326 0.78314316 0.66596755 0.35021133 0.20937906
  0.58035314 0.16187827 0.35133262 0.65545482]
 [0.99174579 0.61479442 0.39574846 0.75057782 0.82019656 0.56842037
  0.46408945 0.95522619 0.92271772 0.60876587]
 [0.12646152 0.0452397  0.54514152 0.19175943 0.97451865 0.26116235
  0.15140121 0.78277474 0.14096396 0.05810975]
 [0.31452367 0.88038508 0.43272038 0.13642716 0.56191802 0.72136455
  0.64543273

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
x5 = np.random.random(30)
x5.mean()

0.5026518659445844

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x6 = np.ones((3,3))

x6[1:-1,1:-1]=0
x6

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
np.pad(x6,pad_width = 1)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 0., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
x7 = np.ones((5,5))
x7
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
x8 = np.ones((8,8))
x8[::2,1::2]=0
x8[1::2,::2]=0
x8

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
x8 = np.array([[0,1],[1,0]])
np.tile(x8,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z) 

[[0.13187457 0.62144795 0.1272043  0.         0.19413683]
 [0.24842928 0.61900842 0.22859979 0.92914752 0.52139146]
 [0.82826914 0.7311099  0.69612364 0.48110957 0.63434703]
 [0.27217902 0.31384611 1.         0.29871594 0.23775177]
 [0.00535308 0.60490848 0.34035654 0.68617995 0.95460473]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
x = np.arange(1,16)
y = np.arange(16,22)
x,y = x.reshape(5,3),y.reshape(3,2)
print(x)
print(y)
# z = np.dot(x,y)
z = x@y
z

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[16 17]
 [18 19]
 [20 21]]


array([[112, 118],
       [274, 289],
       [436, 460],
       [598, 631],
       [760, 802]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x = np.arange(1,11)
x[(3<x)&(x<=8)]*=-1
x

array([ 1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(np.sum(range(5),-1))
np.info(sum)

9
10
 sum(a, axis=None, dtype=None, out=None, keepdims=<no value>,
     initial=<no value>, where=<no value>)

Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator in which the
    elements are summed.  The dtype of `a` is used by default unless `a`
    has an integer dtype of less precision than the default platform
    integer.  In that case, if `a` is signed then the platform integer
    is used while if `a` is unsigned then an unsigned int

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
x = z**z # this one is legal.
2 << z >> 2 # this one doesn't have any use to it.
z <- Z #not true positive array is greater than negative array
1j*z # multiplying by a complex number can happen
z/1/1 # this is basically z.
z<z>z # the integer is not greater than itself as well as not lesser than itself.

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0)/np.array(0) # nan
np.array(0)//np.array(0) # 0
np.array([np.nan]).astype(int).astype(float) #array([-9.22337204e+18])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[-0.23285795  5.35575972 -0.48588785  7.36419367  3.67032069  2.14894705
 -9.9808768   8.94867341  1.56039183 -9.94146788]
[ -1.   6.  -1.   8.   4.   3. -10.   9.   2. -10.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x = np.arange(1,11)
y = np.arange(6,11)
print(np.intersect1d(x,y))

[ 6  7  8  9 10]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
np.seterr(all = 'ignore')

{'divide': 'warn', 'invalid': 'warn', 'over': 'warn', 'under': 'ignore'}

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
x = np.datetime64('today','D')
y = np.timedelta64(1)
tomorrow = x + y
Yesterday = x-y
print(x,tomorrow,Yesterday)

2022-06-16 2022-06-17 2022-06-15


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
x = np.arange('2016-06', '2016-07', dtype = 'datetime64[D]')
x

array(['2016-06-01', '2016-06-02', '2016-06-03', '2016-06-04',
       '2016-06-05', '2016-06-06', '2016-06-07', '2016-06-08',
       '2016-06-09', '2016-06-10', '2016-06-11', '2016-06-12',
       '2016-06-13', '2016-06-14', '2016-06-15', '2016-06-16',
       '2016-06-17', '2016-06-18', '2016-06-19', '2016-06-20',
       '2016-06-21', '2016-06-22', '2016-06-23', '2016-06-24',
       '2016-06-25', '2016-06-26', '2016-06-27', '2016-06-28',
       '2016-06-29', '2016-06-30'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
Z = np.random.uniform(0,12,12)
print(z)
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[[112 118]
 [274 289]
 [436 460]
 [598 631]
 [760 802]]
[11.  3. 10.  0.  1.  5.  4.  5.  4.  0.  2.  5.]
[11.  3. 10.  0.  1.  5.  4.  5.  4.  0.  2.  5.]
[11.  3. 10.  0.  1.  5.  4.  5.  4.  0.  2.  5.]
[11  3 10  0  1  5  4  5  4  0  2  5]
[11.  3. 10.  0.  1.  5.  4.  5.  4.  0.  2.  5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=10)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
z = np.linspace(0,10,11, endpoint = False)
z.sort()
z

array([0.        , 0.90909091, 1.81818182, 2.72727273, 3.63636364,
       4.54545455, 5.45454545, 6.36363636, 7.27272727, 8.18181818,
       9.09090909])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
Z = np.arange(10)
np.add.reduce(Z)
# np.sum(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

True
True


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1 # will get error as assignment destination is read-only

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
z = np.random.random((10,2))
# z.reshape(10,2)
X,Y = z[:,0], z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.05696444 0.73668421 0.52125944 0.65667207 0.63710404 0.64627494
 0.33531882 0.85946496 0.98849802 0.56470838]
[0.48051315 0.67624035 1.25456295 0.6006661  0.82799685 1.18283309
 0.11203759 0.49922679 0.68983049 0.13557104]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
Z = np.random.random(10)
print(z)
Z[Z.argmax()] = 0
print(Z)

[[0.93727151 0.4885652 ]
 [0.57456305 0.461065  ]
 [0.16210591 0.49541203]
 [0.54172775 0.37114587]
 [0.43090697 0.46927683]
 [0.24448827 0.59824475]
 [0.33321649 0.03748977]
 [0.75456984 0.41146613]
 [0.76248181 0.6290865 ]
 [0.5595268  0.0763238 ]]
[0.42411394 0.6521013  0.74688182 0.         0.60560012 0.47513177
 0.46553412 0.38683829 0.28074758 0.75494906]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

83


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.65368283 0.58495739 0.63451492 0.68206209 0.5176793
  0.44351361 0.54748514 0.50305763 0.33699492]
 [0.65368283 0.         1.0079529  0.22610522 0.26125559 0.47879429
  0.38719722 0.99579994 0.23115293 0.32906689]
 [0.58495739 1.0079529  0.         1.10065441 0.87001887 1.07718182
  0.97899017 0.04710683 0.7795659  0.80702046]
 [0.63451492 0.22610522 1.10065441 0.         0.48002588 0.28604597
  0.23595611 1.07972325 0.38832779 0.30665615]
 [0.68206209 0.26125559 0.87001887 0.48002588 0.         0.69214753
  0.58100182 0.86912307 0.18571397 0.4413749 ]
 [0.5176793  0.47879429 1.07718182 0.28604597 0.69214753 0.
  0.1201856  1.04591578 0.54156133 0.31253192]
 [0.44351361 0.38719722 0.97899017 0.23595611 0.58100182 0.1201856
  0.         0.95027403 0.42381148 0.19406735]
 [0.54748514 0.99579994 0.04710683 1.07972325 0.86912307 1.04591578
  0.95027403 0.         0.76957387 0.78246099]
 [0.50305763 0.23115293 0.7795659  0.38832779 0.18571397 0.54156133
  0.42381148 0.7695738

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)
Y = Z.view(np.int32)
print(Y)
Y[:] = Z
print(Y)
print(type(Y[0]))

[12.919972 86.849945 86.858215 18.980627 85.74743  75.60388  86.09542
 92.584335 87.03316  70.44454 ]
[1095678005 1118679852 1118680936 1100470355 1118535343 1117205808
 1118580955 1119431470 1118703866 1116529563]
[12 86 86 18 85 75 86 92 87 70]
<class 'numpy.int32'>


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z) 

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
X = np.random.rand(5, 10)
print(X,X.mean())
# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[0.97704924 0.10518692 0.82826986 0.33989992 0.88508227 0.62380732
  0.0646558  0.75928197 0.96303388 0.1233633 ]
 [0.99984283 0.67681968 0.37311411 0.81346391 0.3601381  0.4082998
  0.8667759  0.39840952 0.71625033 0.40771291]
 [0.55032202 0.37197772 0.52288622 0.29424459 0.55235494 0.13088849
  0.31825506 0.78274121 0.00886995 0.15117232]
 [0.67005534 0.78263392 0.26887964 0.18574851 0.8917469  0.88004186
  0.42900208 0.68799908 0.35169697 0.07555779]
 [0.5586015  0.96767259 0.0188135  0.58352124 0.9467562  0.18021151
  0.29113382 0.37848662 0.39465978 0.05942675]] 0.499536313690956
[[ 0.41008619 -0.46177613  0.26130682 -0.22706313  0.31811922  0.05684427
  -0.50230725  0.19231892  0.39607083 -0.44359974]
 [ 0.39776013  0.07473697 -0.22896859  0.2113812  -0.24194461 -0.19378291
   0.26469319 -0.20367319  0.11416762 -0.1943698 ]
 [ 0.18195077  0.00360647  0.15451497 -0.07412666  0.18398369 -0.23748276
  -0.05011619  0.41436995 -0.3595013  -0.21719893]
 [ 0.14771913  0.26029771 -0.253

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[5 8 5]
 [7 2 6]
 [7 6 4]]
[[7 2 6]
 [7 6 4]
 [5 8 5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())


[[0 2 1 1 1 1 0 2 2 0]
 [2 0 2 0 1 2 1 0 0 2]
 [2 0 2 2 2 0 1 2 2 2]]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.6374946259776093


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print(Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[5. 2. 2. 2. 4. 2. 2. 7. 2. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum) 

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [3]:

D = np.random.uniform(0,1,100)
print(D)
S = np.random.randint(0,10,100)
print(S)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.47893802 0.76118398 0.60294739 0.95854482 0.5065512  0.35808576
 0.77584935 0.12215545 0.24903643 0.31170852 0.90794976 0.9046485
 0.87602334 0.72423572 0.6569461  0.27036858 0.58472619 0.31081303
 0.64330069 0.26217165 0.89639024 0.95494561 0.9982237  0.28639239
 0.87361319 0.30692365 0.59458173 0.32504991 0.17334708 0.44832204
 0.58221439 0.21977816 0.47898069 0.66925281 0.95782665 0.26106201
 0.19418444 0.31271609 0.36692144 0.51814351 0.67576262 0.26585122
 0.7417956  0.08033973 0.51415262 0.03604446 0.45311556 0.13624143
 0.20428368 0.54093126 0.8488504  0.18189464 0.43344021 0.00497956
 0.89962693 0.80890988 0.37132452 0.38373535 0.58692611 0.25904096
 0.14538278 0.97739791 0.64014745 0.1750016  0.4139325  0.35849911
 0.35511425 0.02767834 0.07876637 0.36301324 0.73269273 0.17811909
 0.41253859 0.48377888 0.17639167 0.37306643 0.94083127 0.91964107
 0.43909953 0.97126796 0.36504475 0.39388148 0.8496979  0.8376886
 0.10792148 0.48803532 0.77248293 0.36067328 0.56677754 0.117692

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [2]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.einsum("ij,ji->i", A, B)

array([0.72705227, 0.3996356 , 1.54101466, 0.84809383, 1.26348235])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [7]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
print(Z0)
Z0[::nz+1] = Z
print(Z0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [8]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [9]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [10]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 27) ( 0, 95) ( 8, 28) ( 8, 41) ( 8, 42) ( 8, 88) (10, 53) (10, 65)
 (15, 75) (15, 98) (22, 26) (22, 30) (22, 32) (22, 69) (24, 62) (24, 93)
 (26, 69) (27, 48) (27, 59) (27, 95) (28, 42) (30, 32) (41, 88) (48, 59)
 (53, 65) (55, 92) (55, 97) (62, 93) (75, 98) (92, 97)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [11]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [12]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [13]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [18]:

Z = np.random.randint(0,2,100)
print(Z)
print(np.logical_not(Z, out=Z))

Z = np.random.uniform(-1.0,1.0,100)
print(Z)
print(np.negative(Z, out=Z))


[0 1 1 1 1 0 0 0 0 1 1 1 0 1 1 0 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 1 0 1 1 1 1
 0 0 1 1 0 1 1 1 0 0 0 1 0 1 1 0 1 1 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 1 1 0 1
 0 1 1 1 1 0 1 0 1 0 0 1 1 0 1 0 0 1 0 0 0 0 0 0 0 1]
[1 0 0 0 0 1 1 1 1 0 0 0 1 0 0 1 0 1 1 0 1 1 1 1 1 0 1 1 0 0 0 0 1 0 0 0 0
 1 1 0 0 1 0 0 0 1 1 1 0 1 0 0 1 0 0 1 1 1 1 0 0 1 1 1 0 1 1 1 1 1 0 0 1 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 1 0 1 1 0 1 1 1 1 1 1 1 0]
[-0.42976278 -0.64791751 -0.55976063 -0.66499139  0.53988424  0.25964513
  0.14682734 -0.84296457 -0.47854935  0.26976531 -0.15697271 -0.73096351
  0.28705749 -0.12559991 -0.00873789 -0.92320574  0.23890965  0.55017712
 -0.68264685 -0.67909653 -0.78256239  0.68803913 -0.40533796 -0.45547839
  0.88316737  0.5410238   0.5610023  -0.94652041 -0.30475093  0.27806123
 -0.62297539  0.72787062  0.14911386 -0.31848316  0.09888042  0.49605623
  0.73727676  0.31919756 -0.88281306  0.50317494  0.7234283  -0.08749676
 -0.11502502 -0.87386312  0.05187466 -0.00341394 -0.92250715 -0.94725163
  0.8146

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [19]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 2.02794379  7.37138178  8.42459069  7.49646455  4.65531852  9.66321331
  0.21166411 11.65892862  5.02807574  0.0134277 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [20]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[7.73592568e+00 2.55051078e+00 7.09207944e+00 1.29793369e+01
  1.14700776e+00 1.23633477e+00 5.53516346e+00 3.54381859e+00
  4.80187532e+00 4.59193904e+00]
 [9.32487445e+00 1.98392919e+00 8.59695282e+00 1.42935307e+01
  1.66185105e+00 8.32467609e-01 4.23432212e+00 3.32107824e+00
  3.71742540e+00 6.12897414e+00]
 [5.69773793e+00 2.03329917e+00 1.38179425e-01 1.88035786e+00
  6.20402886e+00 4.79946657e+00 9.29413082e+00 3.98943300e+00
  5.68543046e+00 9.48096512e+00]
 [5.49207668e+00 1.43552286e+00 2.01890251e+00 2.93640300e-01
  2.71498498e+00 1.28073993e+00 1.18611476e+01 4.60062985e-01
  8.67568944e+00 8.87462288e+00]
 [7.17609099e+00 5.52461556e+00 4.93617875e+00 1.36259080e+01
  1.81946203e+00 4.17570319e+00 8.13604892e+00 6.40934442e+00
  7.63609647e+00 4.36950143e+00]
 [8.00510517e+00 1.21919232e-02 8.79237360e+00 1.22154529e+01
  3.71036445e+00 1.31888965e+00 3.40989671e+00 1.02819234e+00
  2.43802996e+00 4.56861476e+00]
 [9.00585028e+00 7.38712543e+00 8.09990938e+00 1.32067950e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [21]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [22]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [23]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [24]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 2 3]
   [4 3 2]
   [2 4 2]]

  [[2 3 0]
   [3 2 3]
   [4 2 1]]

  [[3 0 0]
   [2 3 2]
   [2 1 0]]

  [[0 0 3]
   [3 2 2]
   [1 0 3]]

  [[0 3 3]
   [2 2 3]
   [0 3 3]]

  [[3 3 0]
   [2 3 4]
   [3 3 4]]

  [[3 0 3]
   [3 4 1]
   [3 4 2]]

  [[0 3 3]
   [4 1 4]
   [4 2 2]]]


 [[[4 3 2]
   [2 4 2]
   [2 1 3]]

  [[3 2 3]
   [4 2 1]
   [1 3 4]]

  [[2 3 2]
   [2 1 0]
   [3 4 2]]

  [[3 2 2]
   [1 0 3]
   [4 2 4]]

  [[2 2 3]
   [0 3 3]
   [2 4 3]]

  [[2 3 4]
   [3 3 4]
   [4 3 0]]

  [[3 4 1]
   [3 4 2]
   [3 0 0]]

  [[4 1 4]
   [4 2 2]
   [0 0 4]]]


 [[[2 4 2]
   [2 1 3]
   [1 1 4]]

  [[4 2 1]
   [1 3 4]
   [1 4 0]]

  [[2 1 0]
   [3 4 2]
   [4 0 3]]

  [[1 0 3]
   [4 2 4]
   [0 3 4]]

  [[0 3 3]
   [2 4 3]
   [3 4 0]]

  [[3 3 4]
   [4 3 0]
   [4 0 2]]

  [[3 4 2]
   [3 0 0]
   [0 2 0]]

  [[4 2 2]
   [0 0 4]
   [2 0 0]]]


 [[[2 1 3]
   [1 1 4]
   [0 3 1]]

  [[1 3 4]
   [1 4 0]
   [3 1 3]]

  [[3 4 2]
   [4 0 3]
   [1 3 4]]

  [[4 2 4]
   [0 3 4]
   [3 4 3]]

  [[2 4 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [25]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 6 18  5  7  2]
 [18  9 10 10  9]
 [ 5 10  7 42 13]
 [ 7 10 42  6  7]
 [ 2  9 13  7  5]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [26]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [27]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [28]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [29]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print(Z[np.argpartition(-Z,n)[:n]])

[9997 9998 9999 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [31]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [32]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [35]:
x = np.random.rand(int(5e7))

print(np.power(x,3))
print(x*x*x)
print(np.einsum('i,i,i->i',x,x,x))

[4.40429919e-01 5.10755938e-04 6.18434505e-03 ... 1.41879354e-01
 4.55123882e-02 8.27740143e-01]
[4.40429919e-01 5.10755938e-04 6.18434505e-03 ... 1.41879354e-01
 4.55123882e-02 8.27740143e-01]
[4.40429919e-01 5.10755938e-04 6.18434505e-03 ... 1.41879354e-01
 4.55123882e-02 8.27740143e-01]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [36]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [37]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[3 0 3]
 [3 0 2]
 [4 3 0]
 [1 0 0]
 [1 2 2]
 [1 2 4]
 [0 2 2]
 [0 0 2]
 [0 2 3]
 [2 2 1]]
[[3 0 3]
 [3 0 2]
 [4 3 0]
 [1 0 0]
 [1 2 2]
 [1 2 4]
 [0 2 2]
 [0 0 2]
 [0 2 3]
 [2 2 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [38]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [40]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [41]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.07940607, 0.54341602, 0.31056869, 0.935406  , 0.86050501,
        0.37694395, 0.4192237 , 0.8928034 , 0.7470332 , 0.8186792 ],
       [0.04505063, 0.30830429, 0.17619955, 0.5306978 , 0.4882031 ,
        0.21385722, 0.23784441, 0.50652743, 0.42382545, 0.46447344],
       [0.03628646, 0.24832667, 0.14192163, 0.42745567, 0.39322791,
        0.17225336, 0.19157408, 0.40798742, 0.34137431, 0.37411463],
       [0.01913404, 0.13094397, 0.07483603, 0.22539964, 0.20735116,
        0.09083011, 0.10101803, 0.21513392, 0.18000848, 0.19727262],
       [0.04720943, 0.32307806, 0.18464294, 0.55612855, 0.51159753,
        0.22410514, 0.24924179, 0.53079995, 0.44413494, 0.48673076],
       [0.00851305, 0.05825911, 0.03329577, 0.10028397, 0.09225391,
        0.0404118 , 0.04494457, 0.09571659, 0.08008871, 0.0877698 ],
       [0.01906616, 0.13047939, 0.07457052, 0.22459994, 0.20661549,
        0.09050785, 0.10065962, 0.21437064, 0.17936982, 0.19657271],
       [0.06428766, 0.43995307, 0.2514383

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [44]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [45]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [46]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.1899089   0.19306282]
