<a href="https://colab.research.google.com/github/Harish-aditya/100_numpy_exercises/blob/main/Numpy_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2], dtype = 'int16')
a

array([1, 2], dtype=int16)

In [3]:
a2 = np.array([[1,2],[3,4]],dtype = 'int32')
a2

array([[1, 2],
       [3, 4]], dtype=int32)

In [4]:
a3 = np.array([[[1,2],[3,4],[5,6]]],dtype = 'int64')
a3

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [5]:
# get dimension
print(a.ndim,a2.ndim,a3.ndim)

1 2 3


In [6]:
# get shape
print(a.shape,a2.shape,a3.shape)

(2,) (2, 2) (1, 3, 2)


In [7]:
# get dtype
print(a.dtype,a2.dtype,a3.dtype)

int16 int32 int64


In [8]:
# get itemsize
print(a.itemsize,a2.itemsize,a3.itemsize)

2 4 8


In [9]:
# get total size
print(a.size,a2.size,a3.size)

2 4 6


In [10]:
# get number of bytes (itemsize*size)
print(a.nbytes,a2.nbytes,a3.nbytes)

4 16 48


Acessing, changing specific rows, elements, columns. etc.,

In [11]:
b = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [12]:
# get a specific element [r,c]
b[1,5]

13

In [13]:
# get a specific row
b[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [14]:
# get a specific column
b[:,3]

array([ 4, 11])

In [15]:
#skipping index [start:end:step]
b[0,1:6:3]

array([2, 5])

In [16]:
#replacing a specific value
b[1,5] = 20
print(b)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [17]:
# replacing a group of values
b[0,4:6]=[1,2]
print(b)

[[ 1  2  3  4  1  2  7]
 [ 8  9 10 11 12 20 14]]


In [18]:
a3

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [19]:
# 3d array
a3.shape

(1, 3, 2)

In [20]:
# get specific element (work outside in)
a3[0,2,0]

5

Initialzing different types of array

In [21]:
# all zeros matrix
c = np.zeros(3)
c1 = np.zeros([2,2])
c2 = np.zeros([3,3,3])

In [22]:
print(c,c1,c2, sep = '\n')

[0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [23]:
# ones
d = np.ones(3)
d1 = np.ones([2,2])
d2 = np.ones([3,3,3])

In [24]:
print(d,d1,d2, sep = '\n')

[1. 1. 1.]
[[1. 1.]
 [1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [25]:
# full values
d3 = np.full((2,2),9,dtype="float32")
d3

array([[9., 9.],
       [9., 9.]], dtype=float32)

In [26]:
# any other full_like
d4 = np.full_like(b,4)
d4

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [27]:
# random decimal numbers
d5 = np.random.rand(10,10)
d5

array([[0.80043219, 0.80056005, 0.35986605, 0.14503454, 0.22936636,
        0.07848087, 0.4913531 , 0.80097641, 0.86522072, 0.2123531 ],
       [0.10947206, 0.91289224, 0.03458978, 0.76977013, 0.52059678,
        0.88111461, 0.35745544, 0.66685681, 0.30671682, 0.1219569 ],
       [0.40548847, 0.80525107, 0.63287012, 0.98316738, 0.84214351,
        0.31091787, 0.52347959, 0.08233785, 0.35329967, 0.26587129],
       [0.30587091, 0.91360306, 0.13660595, 0.45802251, 0.13131335,
        0.34507499, 0.57264891, 0.90268315, 0.12760143, 0.16633075],
       [0.82324015, 0.89367484, 0.28383375, 0.69678456, 0.60330634,
        0.93770767, 0.76739929, 0.34425769, 0.97017519, 0.84347188],
       [0.58117892, 0.08040773, 0.87463599, 0.3232623 , 0.34818675,
        0.80752591, 0.54537915, 0.16902215, 0.07304503, 0.44641964],
       [0.91801611, 0.367075  , 0.22635281, 0.38297086, 0.7087346 ,
        0.6271329 , 0.03525748, 0.2713896 , 0.10918315, 0.5668167 ],
       [0.00187848, 0.94181326, 0.0556523

In [28]:
d6 = np.random.randint(10,100,size = (4,4))
d6

array([[11, 85, 71, 44],
       [90, 23, 96, 40],
       [83, 20, 72, 24],
       [56, 17, 88, 14]])

In [29]:
# to create a array with a predefined shape.
d7 = np.random.random_sample(a.shape)
d7

array([0.98437522, 0.31449041])

In [30]:
# to create an identity matrix
d8 = np.identity(3)
d8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
# to repeat an array multiple times.
arr = np.array([1,2,3])
r1 = np.repeat(arr,3,axis = 0)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [32]:

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [33]:
op = np.ones((5,5))
op

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
z[1,1]=9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [36]:
op[1:4,1:4]=z
op

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Be careful when copying arrays.


In [37]:
e = np.array([1,2,3])
f = e
print(f,e)
f[0] = 100


[1 2 3] [1 2 3]


In [38]:
f,e

(array([100,   2,   3]), array([100,   2,   3]))

In [39]:
e = np.array([1,2,3])
f = e.copy()
print(f,e)
f[0] = 100

[1 2 3] [1 2 3]


In [40]:
f,e

(array([100,   2,   3]), array([1, 2, 3]))

### mathematics

In [44]:
e1 = np.array([1,2,3,4])
e1

array([1, 2, 3, 4])

In [45]:
e1 += 3
e1

array([4, 5, 6, 7])

In [47]:
e1 - 2

array([2, 3, 4, 5])

In [48]:
e1 * 3

array([12, 15, 18, 21])

In [50]:
e1/3

array([1.33333333, 1.66666667, 2.        , 2.33333333])

In [51]:
e1 ** 2

array([16, 25, 36, 49])

In [70]:
# take the cos, sin of the array
e2 = np.cos(e1)
e2

array([-0.65364362,  0.28366219,  0.96017029,  0.75390225])

In [81]:
f1 = np.ones((2,3))
print(f1)

f2 = np.full((3,2),2)
print(f2)

f4 = np.matmul(f1,f2)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [84]:
# find the determinant
f3 = np.identity(3)
np.linalg.det(f3),np.linalg.det(f4)

(1.0, 0.0)

determinant,
trace,
single vector displacement,
eigenvalues,
matrixnorm,
inverse,

### statistics

In [86]:
g = np.array([[1,2,3],[2,3,4]])
np.min(g)

1

In [89]:
np.min(g,axis = 0)

array([1, 2, 3])

In [90]:
np.min(g,axis = 1)

array([1, 2])

In [92]:
np.max(g)

4

In [91]:
np.max(g,axis = 0)

array([2, 3, 4])

In [94]:
np.max(g,axis = 1)

array([3, 4])

In [93]:
np.mean(g,axis = 1)

array([2., 3.])

### Reorganizing arrays

In [95]:
bf = np.array([[1,2,3,4],[5,6,7,8]])
print(bf,bf.shape)

[[1 2 3 4]
 [5 6 7 8]] (2, 4)


In [100]:
af1 = bf.reshape((4,2))
af2 = bf.reshape((2,2,2))
print(af1,af2,sep = "\n")

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


vertically stacking vectors

In [102]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

horizontal stacking vectors

In [103]:
np.hstack([v1,v2,v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])