<a href="https://colab.research.google.com/github/Harish-aditya/100_numpy_exercises/blob/main/Numpy_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### basics

In [1]:
import numpy as np

In [2]:
a = np.array([1,2], dtype = 'int16')
a

array([1, 2], dtype=int16)

In [3]:
a2 = np.array([[1,2],[3,4]],dtype = 'int32')
a2

array([[1, 2],
       [3, 4]], dtype=int32)

In [4]:
a3 = np.array([[[1,2],[3,4],[5,6]]],dtype = 'int64')
a3

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [5]:
# get dimension
print(a.ndim,a2.ndim,a3.ndim)

1 2 3


In [6]:
# get shape
print(a.shape,a2.shape,a3.shape)

(2,) (2, 2) (1, 3, 2)


In [7]:
# get dtype
print(a.dtype,a2.dtype,a3.dtype)

int16 int32 int64


In [8]:
# get itemsize
print(a.itemsize,a2.itemsize,a3.itemsize)

2 4 8


In [9]:
# get total size
print(a.size,a2.size,a3.size)

2 4 6


In [10]:
# get number of bytes (itemsize*size)
print(a.nbytes,a2.nbytes,a3.nbytes)

4 16 48


Acessing, changing specific rows, elements, columns. etc.,

In [11]:
b = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [12]:
# get a specific element [r,c]
b[1,5]

13

In [13]:
# get a specific row
b[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [14]:
# get a specific column
b[:,3]

array([ 4, 11])

In [15]:
#skipping index [start:end:step]
b[0,1:6:3]

array([2, 5])

In [16]:
#replacing a specific value
b[1,5] = 20
print(b)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [17]:
# replacing a group of values
b[0,4:6]=[1,2]
print(b)

[[ 1  2  3  4  1  2  7]
 [ 8  9 10 11 12 20 14]]


In [18]:
a3

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [19]:
# 3d array
a3.shape

(1, 3, 2)

In [20]:
# get specific element (work outside in)
a3[0,2,0]

5

Initialzing different types of array

In [21]:
# all zeros matrix
c = np.zeros(3)
c1 = np.zeros([2,2])
c2 = np.zeros([3,3,3])

In [22]:
print(c,c1,c2, sep = '\n')

[0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [23]:
# ones
d = np.ones(3)
d1 = np.ones([2,2])
d2 = np.ones([3,3,3])

In [24]:
print(d,d1,d2, sep = '\n')

[1. 1. 1.]
[[1. 1.]
 [1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [25]:
# full values
d3 = np.full((2,2),9,dtype="float32")
d3

array([[9., 9.],
       [9., 9.]], dtype=float32)

In [26]:
# any other full_like
d4 = np.full_like(b,4)
d4

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [27]:
# random decimal numbers
d5 = np.random.rand(10,10)
d5

array([[0.16137339, 0.87315682, 0.92016393, 0.56027817, 0.01750869,
        0.20725492, 0.74875188, 0.76247802, 0.07270099, 0.87425175],
       [0.57467238, 0.88895808, 0.68378822, 0.93791114, 0.94012774,
        0.37470131, 0.30250607, 0.18322524, 0.84360048, 0.8351154 ],
       [0.48431643, 0.5429336 , 0.69395213, 0.43103068, 0.78753969,
        0.07249778, 0.9667736 , 0.2397965 , 0.70964941, 0.81673012],
       [0.16040791, 0.4454902 , 0.96131329, 0.30519652, 0.25923623,
        0.45383993, 0.09598819, 0.96325724, 0.6128136 , 0.1847276 ],
       [0.99862675, 0.99544586, 0.02764   , 0.81096654, 0.48781901,
        0.03216187, 0.51284648, 0.82670038, 0.21196596, 0.1292803 ],
       [0.12767475, 0.39069527, 0.15715169, 0.21940981, 0.9475723 ,
        0.28391344, 0.47086422, 0.73402981, 0.53879863, 0.44639871],
       [0.49726983, 0.83139193, 0.47575368, 0.5516944 , 0.12096002,
        0.14329991, 0.06241571, 0.38901785, 0.40222568, 0.59585208],
       [0.62641896, 0.56285368, 0.0032469

In [28]:
d6 = np.random.randint(10,100,size = (4,4))
d6

array([[32, 99, 36, 33],
       [66, 64, 46, 82],
       [99, 45, 19, 75],
       [29, 66, 87, 66]])

In [29]:
# to create a array with a predefined shape.
d7 = np.random.random_sample(a.shape)
d7

array([0.55672104, 0.84447287])

In [30]:
# to create an identity matrix
d8 = np.identity(3)
d8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
# to repeat an array multiple times.
arr = np.array([1,2,3])
r1 = np.repeat(arr,3,axis = 0)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [32]:

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [33]:
op = np.ones((5,5))
op

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
z[1,1]=9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [36]:
op[1:4,1:4]=z
op

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Be careful when copying arrays.


In [37]:
e = np.array([1,2,3])
f = e
print(f,e)
f[0] = 100


[1 2 3] [1 2 3]


In [38]:
f,e

(array([100,   2,   3]), array([100,   2,   3]))

In [39]:
e = np.array([1,2,3])
f = e.copy()
print(f,e)
f[0] = 100

[1 2 3] [1 2 3]


In [40]:
f,e

(array([100,   2,   3]), array([1, 2, 3]))

### mathematics

In [41]:
e1 = np.array([1,2,3,4])
e1

array([1, 2, 3, 4])

In [42]:
e1 += 3
e1

array([4, 5, 6, 7])

In [43]:
e1 - 2

array([2, 3, 4, 5])

In [44]:
e1 * 3

array([12, 15, 18, 21])

In [45]:
e1/3

array([1.33333333, 1.66666667, 2.        , 2.33333333])

In [46]:
e1 ** 2

array([16, 25, 36, 49])

In [47]:
# take the cos, sin of the array
e2 = np.cos(e1)
e2

array([-0.65364362,  0.28366219,  0.96017029,  0.75390225])

In [48]:
f1 = np.ones((2,3))
print(f1)

f2 = np.full((3,2),2)
print(f2)

f4 = np.matmul(f1,f2)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [49]:
# find the determinant
f3 = np.identity(3)
np.linalg.det(f3),np.linalg.det(f4)

(1.0, 0.0)

determinant,
trace,
single vector displacement,
eigenvalues,
matrixnorm,
inverse,

### statistics

In [50]:
g = np.array([[1,2,3],[2,3,4]])
np.min(g)

1

In [51]:
np.min(g,axis = 0)

array([1, 2, 3])

In [52]:
np.min(g,axis = 1)

array([1, 2])

In [53]:
np.max(g)

4

In [54]:
np.max(g,axis = 0)

array([2, 3, 4])

In [55]:
np.max(g,axis = 1)

array([3, 4])

In [56]:
np.mean(g,axis = 1)

array([2., 3.])

### Reorganizing arrays

In [57]:
bf = np.array([[1,2,3,4],[5,6,7,8]])
print(bf,bf.shape)

[[1 2 3 4]
 [5 6 7 8]] (2, 4)


In [58]:
af1 = bf.reshape((4,2))
af2 = bf.reshape((2,2,2))
print(af1,af2,sep = "\n")

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


vertically stacking vectors

In [59]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

horizontal stacking vectors

In [60]:
np.hstack([v1,v2,v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

### Miscellaneous

In [61]:
dd = np.genfromtxt('/content/testt.txt', delimiter = ',')

OSError: ignored

In [ ]:
dd.astype('int32')

### boolean masking and advanced indexing

In [ ]:
dd > 5

In [ ]:
dd[dd>5]

In [ ]:
# you can index with a list in numpy
aa = np.array([6.,  7.,  8.,  9., 10.,  6.,  7.,  8.,  9., 11.])
aa


In [ ]:
# indexing with slicing
aa[2:]

In [ ]:
# indexing with location
aa[[1,2,3]]

In [ ]:
np.all(dd > 5)

In [ ]:
np.any(dd > 5)

In [ ]:
((dd > 5) & (dd <8))

In [ ]:
(~(dd > 5) & (dd <8))

In [ ]:
bb = np.random.randint(1,10,size=(5,5))

In [ ]:
bb

In [ ]:
bb[2:4,:2]

In [ ]:
bb[[1,2,3],[0,1,2]]

In [ ]:
bb[[0,3,4],3:]