<a href="https://colab.research.google.com/github/Harish-aditya/100_numpy_exercises/blob/main/Numpy_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2], dtype = 'int16')
a

array([1, 2], dtype=int16)

In [3]:
a2 = np.array([[1,2],[3,4]],dtype = 'int32')
a2

array([[1, 2],
       [3, 4]], dtype=int32)

In [4]:
a3 = np.array([[[1,2],[3,4],[5,6]]],dtype = 'int64')
a3

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [5]:
# get dimension
print(a.ndim,a2.ndim,a3.ndim)

1 2 3


In [6]:
# get shape
print(a.shape,a2.shape,a3.shape)

(2,) (2, 2) (1, 3, 2)


In [7]:
# get dtype
print(a.dtype,a2.dtype,a3.dtype)

int16 int32 int64


In [8]:
# get itemsize
print(a.itemsize,a2.itemsize,a3.itemsize)

2 4 8


In [9]:
# get total size
print(a.size,a2.size,a3.size)

2 4 6


In [10]:
# get number of bytes (itemsize*size)
print(a.nbytes,a2.nbytes,a3.nbytes)

4 16 48


Acessing, changing specific rows, elements, columns. etc.,

In [11]:
b = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [12]:
# get a specific element [r,c]
b[1,5]

13

In [13]:
# get a specific row
b[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [14]:
# get a specific column
b[:,3]

array([ 4, 11])

In [15]:
#skipping index [start:end:step]
b[0,1:6:3]

array([2, 5])

In [16]:
#replacing a specific value
b[1,5] = 20
print(b)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [17]:
# replacing a group of values
b[0,4:6]=[1,2]
print(b)

[[ 1  2  3  4  1  2  7]
 [ 8  9 10 11 12 20 14]]


In [18]:
a3

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [19]:
# 3d array
a3.shape

(1, 3, 2)

In [20]:
# get specific element (work outside in)
a3[0,2,0]

5

Initialzing different types of array

In [21]:
# all zeros matrix
c = np.zeros(3)
c1 = np.zeros([2,2])
c2 = np.zeros([3,3,3])

In [22]:
print(c,c1,c2, sep = '\n')

[0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [23]:
# ones
d = np.ones(3)
d1 = np.ones([2,2])
d2 = np.ones([3,3,3])

In [24]:
print(d,d1,d2, sep = '\n')

[1. 1. 1.]
[[1. 1.]
 [1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [25]:
# full values
d3 = np.full((2,2),9,dtype="float32")
d3

array([[9., 9.],
       [9., 9.]], dtype=float32)

In [26]:
# any other full_like
d4 = np.full_like(b,4)
d4

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [27]:
# random decimal numbers
d5 = np.random.rand(10,10)
d5

array([[0.40399409, 0.37742032, 0.61721311, 0.66597364, 0.24184081,
        0.70715759, 0.47296053, 0.90217422, 0.22610969, 0.29306582],
       [0.46961098, 0.21828394, 0.14522413, 0.23506254, 0.53301319,
        0.58026816, 0.63291471, 0.46466164, 0.04775618, 0.27458889],
       [0.21337919, 0.13930795, 0.53069349, 0.12760602, 0.20469144,
        0.05228289, 0.27069593, 0.98332119, 0.53946051, 0.52978358],
       [0.23469368, 0.51247886, 0.39794356, 0.50302829, 0.63211055,
        0.0167201 , 0.5412227 , 0.93744904, 0.34433103, 0.9414958 ],
       [0.67524561, 0.3959372 , 0.08365414, 0.58035136, 0.60333211,
        0.92012033, 0.50077632, 0.83856971, 0.84420867, 0.65526472],
       [0.37345862, 0.25714047, 0.73846588, 0.44241514, 0.78566268,
        0.53976634, 0.26407204, 0.59810364, 0.9351605 , 0.28320583],
       [0.77394509, 0.32532094, 0.73242233, 0.55835376, 0.02069736,
        0.9078443 , 0.96566455, 0.40613242, 0.05354663, 0.00289904],
       [0.25620317, 0.23639841, 0.0470998

In [28]:
d6 = np.random.randint(10,100,size = (4,4))
d6

array([[16, 26, 83, 11],
       [47, 36, 94, 93],
       [20, 19, 47, 92],
       [42, 16, 10, 47]])

In [29]:
# to create a array with a predefined shape.
d7 = np.random.random_sample(a.shape)
d7

array([0.26534069, 0.67387139])

In [34]:
# to create an identity matrix
d8 = np.identity(3)
d8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
# to repeat an array multiple times.
arr = np.array([1,2,3])
r1 = np.repeat(arr,3,axis = 0)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [39]:

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [40]:
op = np.ones((5,5))
op

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
z = np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
z[1,1]=9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [47]:
op[1:4,1:4]=z
op

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Be careful when copying arrays.


In [51]:
e = np.array([1,2,3])
f = e
print(f,e)
f[0] = 100


[1 2 3] [1 2 3]


In [52]:
f,e

(array([100,   2,   3]), array([100,   2,   3]))

In [53]:
e = np.array([1,2,3])
f = e.copy()
print(f,e)
f[0] = 100

[1 2 3] [1 2 3]


In [54]:
f,e

(array([100,   2,   3]), array([1, 2, 3]))