<a href="https://colab.research.google.com/github/Harish-aditya/100_numpy_exercises/blob/main/Numpy_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2], dtype = 'int16')
a

array([1, 2], dtype=int16)

In [3]:
a2 = np.array([[1,2],[3,4]],dtype = 'int32')
a2

array([[1, 2],
       [3, 4]], dtype=int32)

In [4]:
a3 = np.array([[[1,2],[3,4],[5,6]]],dtype = 'int64')
a3

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [5]:
# get dimension
print(a.ndim,a2.ndim,a3.ndim)

1 2 3


In [6]:
# get shape
print(a.shape,a2.shape,a3.shape)

(2,) (2, 2) (1, 3, 2)


In [7]:
# get dtype
print(a.dtype,a2.dtype,a3.dtype)

int16 int32 int64


In [8]:
# get itemsize
print(a.itemsize,a2.itemsize,a3.itemsize)

2 4 8


In [9]:
# get total size
print(a.size,a2.size,a3.size)

2 4 6


In [10]:
# get number of bytes (itemsize*size)
print(a.nbytes,a2.nbytes,a3.nbytes)

4 16 48


Acessing, changing specific rows, elements, columns. etc.,

In [14]:
b = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [15]:
# get a specific element [r,c]
b[1,5]

13

In [17]:
# get a specific row
b[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [22]:
# get a specific column
b[:,3]

array([ 4, 11])

In [26]:
#skipping index [start:end:step]
b[0,1:6:3]

array([2, 5])

In [28]:
#replacing a specific value
b[1,5] = 20
print(b)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [29]:
# replacing a group of values
b[0,]=1
print(b)

[[ 1  1  1  1  1  1  1]
 [ 8  9 10 11 12 20 14]]
